trigger :
- none

stages:

- stage: Terraform
  pool:
    vmImage: 'windows-latest'
  jobs:
    - job: Terraform_Deploy
      steps:
      - pwsh: |
          $dateParam = Get-Date -Format "dd/MM/yyyy-HH" 
          Write-Output "##vso[task.setvariable variable=dateParam;]$dateParam"
          Write-Output "--------------------------"
          Write-Output $env:dateParam

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
        displayName: 'Install Terraform latest'

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
        displayName: 'Terraform : init'
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
          backendServiceArm: 'AI-TDA-SC'
          backendAzureRmResourceGroupName: tfstate
          backendAzureRmStorageAccountName: tfstatebackendlogsacc
          backendAzureRmContainerName: tfstate
          backendAzureRmKey: terraform.tfstate

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
        displayName: 'Terraform : plan'
        inputs:
          command: plan
          commandOptions: '-out plan.out'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
          environmentServiceNameAzureRM: 'AI-TDA-SC'
          backendServiceArm: 'AI-TDA-SC'
          backendAzureRmResourceGroupName: tfstate
          backendAzureRmStorageAccountName: tfstatebackendlogsacc
          backendAzureRmContainerName: tfstate
          backendAzureRmKey: terraform.tfstate

      - powershell: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          ls

      - task: AzureFileCopy@5
        displayName: 'AzureBlob File Copy'
        inputs:
          SourcePath: '$(System.DefaultWorkingDirectory)/Terraform/plan.out'
          azureSubscription: 'AI-TDA-SC'
          Destination: AzureBlob
          storage: tfstatebackendlogsacc
          ContainerName: containerplanout
          BlobPrefix: '$(dateParam)'

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
        displayName: 'Terraform : azurerm'
        inputs:
          command: apply
          workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
          environmentServiceNameAzureRM: 'AI-TDA-SC'
          backendServiceArm: 'AI-TDA-SC'
          backendAzureRmResourceGroupName: tfstate
          backendAzureRmStorageAccountName: tfstatebackendlogsacc
          backendAzureRmContainerName: tfstate
          backendAzureRmKey: terraform.tfstate